-- Seed book list, from titles selected in the existing form responses.
insert into books (title) values
  ('Alloh sari 20 bekat'),
  ('Assasin'),
  ('Aytma, bilmay qo''ya qolsinlar'),
  ('Binafsha shulasi'),
  ('Binafsha shulasi (2)'),
  ('Boy bolishni istasangiz'),
  ('Darbadar'),
  ('Enteresta'),
  ('Er-Xotinga nasihat'),
  ('Farzand tarbiyasida 700 saboq (2-qism)'),
  ('Farzand tarbiyasida 700 saboq (3-qism)'),
  ('Farzand tarbiyasida 700 saboq 1 qism'),
  ('Fotimaning bolasi'),
  ('Habibimiz oramizda bo''lsalar'),
  ('Hayz va nifos hukmlari'),
  ('Ishonchli xabar'),
  ('Jannat bo''stonidagi oilaviy oqshomlar'),
  ('Kelishda non olib keling'),
  ('Labbay Allohim Labbay'),
  ('Lanatlangan qiz'),
  ('Marhumlar kollektsioneri'),
  ('Metin qoyalar'),
  ('O''rgating Allohim'),
  ('Og''riqlardan saboqlar'),
  ('Oqshom go''zaliklari'),
  ('Qalbi singanlarga'),
  ('Qulogim senda qizim'),
  ('Qur''on bilan hamnafas'),
  ('Qur''on qalbiga safar'),
  ('Qur''ondan maktublar'),
  ('Rasulullohdan maktublar'),
  ('Sahobalardan maktublar'),
  ('Shaxmit ustidagi qotiliq'),
  ('Til sayqali'),
  ('Tobeinlardan maktublar'),
  ('Tur, o''rningga yot'),
  ('Yangi Nafas'),
  ('Yosh qizga nasixat'),
  ('Yosh yigitga nasihat'),
  ('Yusufning qizi'),
  ('Кечир Аллохим')
on conflict (title) do nothing;
